name: Release

on:
  push:
    branches:
      - master
      - topic/**
    tags:
      - v*

  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: '1.21'

      - name: Cache go module
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build binary
        env:
          BUILDNUMBER: ${{ github.run_number }}
        run: |
          make -j release
          ls -lash bin

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*
          draft: false
          prerelease: false
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          append_body: true
